target("CppUtils-System")
	set_kind("static")
	set_policy("build.merge_archive", true)
	add_deps("CppUtils-Platform")
	add_includedirs("include", { public = true })
	add_headerfiles("include/**.hpp")
