name: "CI C++: Windows MSYS2"

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.os.name }} (${{ matrix.compiler.cxx }}, ${{ matrix.library-type }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
          name: "Windows",
          value: windows-latest
        }
        compiler:
        - {
          cc: "gcc",
          cxx: "g++",
          install: "mingw-w64-x86_64-gcc"
        }
        - {
          cc: "clang",
          cxx: "clang++",
          install: "mingw-w64-x86_64-clang"
        }
        library-type: [static, shared]
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          ${{ matrix.compiler.install }}
          mingw-w64-x86_64-xmake
    - name: Compile
      shell: msys2 {0}
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f -p mingw -k ${{ matrix.library-type }} -v
        xmake -vD
    - name: Run tests
      shell: msys2 {0}
      run: |
        xmake run
