name: "CI C++: Linux"

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.os.name }} (${{ matrix.compiler.cxx }}, ${{ matrix.library-type }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
          name: "Ubuntu",
          value: ubuntu-latest
        }
        compiler:
        - {
          cc: "clang",
          cxx: "clang++"
        }
        library-type: [static, shared]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: MorganCaron/clang-precompiled-action@master
    - name: Install XMake
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:xmake-io/xmake
        sudo apt update
        sudo apt install xmake
    - name: Compile
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f --toolchain=llvm --sdk=llvm/ --runtimes="c++_shared" --enable_tests=y --yes
        xmake build
    - name: Run tests
      run: |
        xmake run
