name: "CI C++: MacOS"

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.os.name }} (${{ matrix.compiler.cxx }}, ${{ matrix.library-type }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - {
          name: "MacOS",
          value: macos-11
        }
        compiler:
        - {
          cc: "gcc",
          cxx: "g++"
        }
        - {
          cc: "clang",
          cxx: "clang++"
        }
        library-type: [static, shared]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install LLVM
      run: |
        brew install llvm
    - name: Install XMake
      run: brew install xmake
    - name: Compile
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f -p macosx -k ${{ matrix.library-type }} -v
        xmake -vD
    - name: Run tests
      run: |
        xmake run
