name: "CI C++: Windows MSYS2"

on: [ push, pull_request ]

jobs:
  build:
    name: Windows MSYS2 (${{ matrix.compiler.name }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - {
          name: "GCC",
          cc: "gcc",
          cxx: "g++",
          install: "mingw-w64-x86_64-gcc"
        }
        - {
          name: "Clang",
          cc: "clang",
          cxx: "clang++",
          install: "mingw-w64-x86_64-clang"
        }
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          ${{ matrix.compiler.install }}
          mingw-w64-x86_64-xmake

    - name: Compile
      shell: msys2 {0}
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f --runtimes="c++_shared" --enable_tests=y --yes
        xmake build -vD

    - name: Run tests
      shell: msys2 {0}
      run: |
        xmake run
