name: "CI C++: Windows MSYS2"

on: [ push, pull_request ]

jobs:
  build:
    name: Windows MSYS2 (${{ matrix.compiler.name }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - {
          name: "GCC",
          cc: "gcc",
          cxx: "g++",
          install: "mingw-w64-x86_64-gcc"
        }
        - {
          name: "Clang",
          cc: "clang",
          cxx: "clang++",
          install: "mingw-w64-x86_64-clang"
        }
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          base-devel
          unzip
          p7zip
          ${{ matrix.compiler.install }}
        update: true

    - name: Install XMake
      shell: msys2 {0}
      run: |
          git clone https://github.com/xmake-io/xmake.git --recurse-submodules -b master
          pushd xmake
          ./configure
          make -j4
          make install PREFIX=/mingw64
          xmake --version
          popd

    - name: Compile
      shell: msys2 {0}
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f --enable_tests=y --yes
        xmake build -vD

    - name: Run tests
      shell: msys2 {0}
      run: |
        xmake run
