name: "CI C++: MacOS"

on: [ push, pull_request ]

jobs:
  build:
    name: MacOS (${{ matrix.compiler.name }})
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - {
          name: "Clang",
          cc: "clang",
          cxx: "clang++"
        }
    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@master

    - name: Install LLVM
      if: ${{ matrix.compiler.name == 'Clang' }}
      run: |
        brew install llvm

    - name: Compile
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        xmake f --runtimes="c++_shared" --enable_tests=y --yes
        xmake build -vD

    - name: Run tests
      run: |
        xmake run
